import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


import ThemeProviders from "@/providers/ThemeProviders";

// import context
import { GlobalProvider } from '../context/GlobalContext'
import CookiesProviders from "@/providers/CookiesProviders";
import { ReactQueryWrapper } from "@/providers/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<GlobalProvider>
					<CookiesProviders>
						<ReactQueryWrapper>
							<ThemeProviders>
								{children}
							</ThemeProviders>
						</ReactQueryWrapper>
					</CookiesProviders>
				</GlobalProvider>
			</body>
		</html>
	);
}
