# Generated by Django 5.0.4 on 2024-04-09 07:02

import django.db.models.deletion
import user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=user.models.get_profile_image_upload_path)),
                ('email_verification_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('email_verification_otp_expired_at', models.DateTimeField(blank=True, null=True)),
                ('email_verification_code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('auth_user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'profiles',
                'db_table': 'profile',
                'ordering': ['id'],
            },
        ),
    ]
