# Generated by Django 5.0.4 on 2024-04-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
