# Generated by Django 5.0.4 on 2024-04-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='price',
            new_name='amount',
        ),
    ]
