# Generated by Django 5.0.4 on 2024-04-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_rename_price_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('INCOME', 'INCOME'), ('EXPENSE', 'EXPENSE')], default=None, max_length=10),
        ),
    ]
