# Generated by Django 5.0.4 on 2024-04-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
    ]
